// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC82eQK4KZgLLPZrd2nwg7kNiKNHEQYIyw',
    appId: '1:1023988305900:web:4bb037b7e715bb6ebc7ac9',
    messagingSenderId: '1023988305900',
    projectId: 'wingspan-staging-de2ae',
    authDomain: 'wingspan-staging-de2ae.firebaseapp.com',
    storageBucket: 'wingspan-staging-de2ae.appspot.com',
    measurementId: 'G-N0R4CYCJPQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6tg14ot5vp8g2QHBJo5sY6iPQ0lDmtwY',
    appId: '1:1023988305900:android:3bc0814768f82792bc7ac9',
    messagingSenderId: '1023988305900',
    projectId: 'wingspan-staging-de2ae',
    storageBucket: 'wingspan-staging-de2ae.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPqbW73i9Rr1bRyf4cNq917lWRzDigi6k',
    appId: '1:1023988305900:ios:5b5fd9a2335e44a9bc7ac9',
    messagingSenderId: '1023988305900',
    projectId: 'wingspan-staging-de2ae',
    storageBucket: 'wingspan-staging-de2ae.appspot.com',
    iosBundleId: 'com.aapico.appname',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPqbW73i9Rr1bRyf4cNq917lWRzDigi6k',
    appId: '1:1023988305900:ios:5b5fd9a2335e44a9bc7ac9',
    messagingSenderId: '1023988305900',
    projectId: 'wingspan-staging-de2ae',
    storageBucket: 'wingspan-staging-de2ae.appspot.com',
    iosBundleId: 'com.aapico.appname',
  );
}
